apiVersion: v1
kind: Service
metadata:
  name: go-api
spec:
  selector:
    app: go-api
  ports:
  - name: health-check
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: ping
    port: 8080
    protocol: TCP
    targetPort: 8080

  
